Added auto video converter progress in gui.

diff --git a/rootfs/etc/services.d/autovideoconverter/run b/rootfs/etc/services.d/autovideoconverter/run
--- a/rootfs/etc/services.d/autovideoconverter/run
+++ b/rootfs/etc/services.d/autovideoconverter/run
@@ -73,12 +73,19 @@ log() {
 }
 
 log_hb_encode_progress() {
+    YAD_FD="${1:-UNSET}"
     LINE_COUNT=0
     while read OUTPUT; do
+        L="$(echo "$OUTPUT" | cut -d',' -f2- | sed 's/^ *//')"
         if [ "$(expr $LINE_COUNT % 6)" = "0" ]; then
-            log "Encoding:$(echo "$OUTPUT" | cut -d',' -f2-)"
+            log "Encoding: $L"
         fi
         LINE_COUNT="$(expr $LINE_COUNT + 1)"
+
+        if [ "$YAD_FD" != "UNSET" ]; then
+            echo "$L" | cut -d ' ' -f1 >&$YAD_FD
+            echo "# $L" >&$YAD_FD
+        fi
     done
 }
 
@@ -242,6 +249,41 @@ process_video() {
         # Set the temporary output filename.
         OUTPUT_FILE_TMP="$OUTPUT_DIR_TMP/$basename.$AC_FORMAT"
 
+        # Create a named pipe for the progress window.
+        if [ "${AUTOMATED_CONVERSION_NO_GUI_PROGRESS:-0}" -eq 0 ]; then
+            YAD_NP="$(mktemp)"
+            YAD_NP_FD=6
+            rm "$YAD_NP" && mkfifo "$YAD_NP"
+            if [ "$?" -ne 0 ]; then
+                log "WARNING: Failed to create named pipe for UI progress."
+                rm "$YAD_NP"
+                YAD_NP="UNSET"
+            else
+                # Open a read/write file descriptor so we can write to the named
+                # pipe without blocking.
+                exec $YAD_NP_FD<> "$YAD_NP"
+            fi
+        else
+            YAD_NP="UNSET"
+            YAD_NP_FD="UNSET"
+        fi
+
+        # Open the progress window in background.
+        if [ "$YAD_NP" != "UNSET" ]; then
+            yad --fixed \
+                --width=384 \
+                --posx=$(expr $DISPLAY_WIDTH / 2 - 384 / 2) \
+                --posy=5 \
+                --title "Automatic Video Converter" \
+                --window-icon /opt/novnc/images/icons/master_icon.png \
+                --borders 10 \
+                --text "Encoding $video..." \
+                --no-buttons \
+                --auto-close \
+                --progress \
+                < "$YAD_NP" &
+        fi
+
         # Invoke HandBrake.
         echo "------- CONVERSION OUTPUT $(date) -------" >> \
             /config/log/hb/conversion.log
@@ -251,8 +293,17 @@ process_video() {
                        --preset "$AC_PRESET" 2>> \
             /config/log/hb/conversion.log \| \
             /usr/bin/unbuffer -p grep "^Encoding" \| \
-            log_hb_encode_progress
+            log_hb_encode_progress "$YAD_NP_FD"
         hb_rc=$pipestatus_1
+
+        if [ "$YAD_NP" != "UNSET" ]; then
+            # Make sure to close the progress window.
+            echo 100 >&$YAD_NP_FD
+
+            # Close the file descriptor and remove the named pipe.
+            exec $YAD_NP_FD<&-
+            rm "$YAD_NP"
+        fi
 
         # Move the file to its final location if conversion terminated
         # successfully.
